### ISSUE TITLE
request - provide an easy way to ignore pods files

### ISSUE THREAD

**Issue by ConfusedVorlon** [onesky/plugin-xcode#7]
Like most developers these days, I use cocoapods.
These generate a lot of source files with Pods-<target>-<filename>.m

I don't want these files localized. A checkbox to exclude podfiles would be an appropriate fix.

![2015-01-19 03 36 20 pm](https://cloud.githubusercontent.com/assets/586910/5802892/1164a66c-9ff1-11e4-8903-3bc56e151834.png)

**Comment by bretdabaker** [comment]
Thanks for reporting this, I will work out a better file selection UI in the generate/send strings dialogs.

**Comment by ConfusedVorlon** [comment]
Before I came across this plugin, I wrote some code which was going to do much the same job. I approached it by parsing the xcproj file to find which source files were included in a given target.

The code is here, and you're welcome to use it if you like:

https://github.com/ConfusedVorlon/ProjectFileTool

it would let you auto-select files that the developer had selected in a target.

**Comment by bretdabaker** [comment]
Hi, the dialog should only generate/update .strings files for the target selected in the `Project Properties`. It's fixed in this release:

https://github.com/onesky/plugin-xcode/releases/tag/1.4.8

**Comment by ConfusedVorlon** [comment]
I downloaded 1.4.8 and it still isn't working.

I created a demo project (completely blank boilerplate project), and added a pod for AFNetworking.

running 'generate strings' gives me the following

![2015-01-27 10 24 43 am](https://cloud.githubusercontent.com/assets/586910/5916921/e71f0a7c-a60e-11e4-99a5-c919f3e1a097.png)

the only file in the target is actually AppDelegate.m

**Comment by bretdabaker** [comment]
Did you restart Xcode? This is the old version.

**Comment by ConfusedVorlon** [comment]
yes, then I deleted redownloaded, and tried again.

I just checked your zip file, it has the 1.4.6 version (according to the plist)

**Comment by bretdabaker** [comment]
Sorry, will check and fix it.

**Comment by ConfusedVorlon** [comment]
thank you.
